[package]
name = "friday-rust-lib"
version = "0.1.2"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] }
# rodio = "0.19.0"
tts_rust = "0.3.5"
# vosk = "0.2.0"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0"
