[package]
name = "tts"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
hound = "3.5.1"
pyo3 = { version = "0.22.2", features = ["extension-module"] }
tts_rust = "0.3.5"

[lib]
crate-type = ["cdylib"]
